from flask import Flask, request, jsonify
from datetime import datetime

app = Flask(__name__)

valid_keys = {
    "TEST1": {"is_used": False, "device_id": None, "last_verified": None},
    "TEST2": {"is_used": False, "device_id": None, "last_verified": None},
    "TEST3": {"is_used": False, "device_id": None, "last_verified": None},
    "TEST4": {"is_used": False, "device_id": None, "last_verified": None},
    "SANSFE-CUSTOM-1535": {"is_used": False, "device_id": None, "last_verified": None},
    "913ac": {"is_used": False, "device_id": None, "last_verified": None},
    "482jd": {"is_used": False, "device_id": None, "last_verified": None},
    "594uz": {"is_used": False, "device_id": None, "last_verified": None},
    "7c4ef70e4a": {"is_used": False, "device_id": None, "last_verified": None},
    "Cd7540e90a": {"is_used": False, "device_id": None, "last_verified": None},
    "fb72fb95d7": {"is_used": False, "device_id": None, "last_verified": None},
    "712mf": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHARCUSTOM-344": {"is_used": False, "device_id": None, "last_verified": None},
    "384qc": {"is_used": False, "device_id": None, "last_verified": None},
    "105rn": {"is_used": False, "device_id": None, "last_verified": None},
    "824yt": {"is_used": False, "device_id": None, "last_verified": None},
    "347ox": {"is_used": False, "device_id": None, "last_verified": None},
    "993be": {"is_used": False, "device_id": None, "last_verified": None},
    "641nv": {"is_used": False, "device_id": None, "last_verified": None},
    "238lf": {"is_used": False, "device_id": None, "last_verified": None},
    "750za": {"is_used": False, "device_id": None, "last_verified": None},
    "614ws": {"is_used": False, "device_id": None, "last_verified": None},
    "498cj": {"is_used": False, "device_id": None, "last_verified": None},
    "857gm": {"is_used": False, "device_id": None, "last_verified": None},
    "176pb": {"is_used": False, "device_id": None, "last_verified": None},
    "321qd": {"is_used": False, "device_id": None, "last_verified": None},
    "463ua": {"is_used": False, "device_id": None, "last_verified": None},
    "291do": {"is_used": False, "device_id": None, "last_verified": None},
    "725hr": {"is_used": False, "device_id": None, "last_verified": None},
    "108mk": {"is_used": False, "device_id": None, "last_verified": None},
    "672ex": {"is_used": False, "device_id": None, "last_verified": None},
    "945sj": {"is_used": False, "device_id": None, "last_verified": None},
    "509vt": {"is_used": False, "device_id": None, "last_verified": None},
    "843yn": {"is_used": False, "device_id": None, "last_verified": None},
    "367ti": {"is_used": False, "device_id": None, "last_verified": None},
    "222ku": {"is_used": False, "device_id": None, "last_verified": None},
    "136bg": {"is_used": False, "device_id": None, "last_verified": None},
    "956zy": {"is_used": False, "device_id": None, "last_verified": None},
    "819rw": {"is_used": False, "device_id": None, "last_verified": None},
    "704mc": {"is_used": False, "device_id": None, "last_verified": None},
    "611fx": {"is_used": False, "device_id": None, "last_verified": None},
    "459na": {"is_used": False, "device_id": None, "last_verified": None},
    "828dp": {"is_used": False, "device_id": None, "last_verified": None},
    "190th": {"is_used": False, "device_id": None, "last_verified": None},
    "330qe": {"is_used": False, "device_id": None, "last_verified": None},
    "673bu": {"is_used": False, "device_id": None, "last_verified": None},
    "504yw": {"is_used": False, "device_id": None, "last_verified": None},
    "266ok": {"is_used": False, "device_id": None, "last_verified": None},
    "718ls": {"is_used": False, "device_id": None, "last_verified": None},
    "144hv": {"is_used": False, "device_id": None, "last_verified": None},
    "935zi": {"is_used": False, "device_id": None, "last_verified": None},
    "287cg": {"is_used": False, "device_id": None, "last_verified": None},
    "477mn": {"is_used": False, "device_id": None, "last_verified": None},
    "682tx": {"is_used": False, "device_id": None, "last_verified": None},
    "352ay": {"is_used": False, "device_id": None, "last_verified": None},
    "466fb": {"is_used": False, "device_id": None, "last_verified": None},
    "118vo": {"is_used": False, "device_id": None, "last_verified": None},
    "799eb": {"is_used": False, "device_id": None, "last_verified": None},
    "221jd": {"is_used": False, "device_id": None, "last_verified": None},
    "938xl": {"is_used": False, "device_id": None, "last_verified": None},
    "154wr": {"is_used": False, "device_id": None, "last_verified": None},
    "447ny": {"is_used": False, "device_id": None, "last_verified": None},
    "613ab": {"is_used": False, "device_id": None, "last_verified": None},
    "730ge": {"is_used": False, "device_id": None, "last_verified": None},
    "871ql": {"is_used": False, "device_id": None, "last_verified": None},
    "299hf": {"is_used": False, "device_id": None, "last_verified": None},
    "168mk": {"is_used": False, "device_id": None, "last_verified": None},
    "823ro": {"is_used": False, "device_id": None, "last_verified": None},
    "451cv": {"is_used": False, "device_id": None, "last_verified": None},
    "705uz": {"is_used": False, "device_id": None, "last_verified": None},
    "990ly": {"is_used": False, "device_id": None, "last_verified": None},
    "302wp": {"is_used": False, "device_id": None, "last_verified": None},
    "625dr": {"is_used": False, "device_id": None, "last_verified": None},
    "474xs": {"is_used": False, "device_id": None, "last_verified": None},
    "214gk": {"is_used": False, "device_id": None, "last_verified": None},
    "870uv": {"is_used": False, "device_id": None, "last_verified": None},
    "143nc": {"is_used": False, "device_id": None, "last_verified": None},
    "368yb": {"is_used": False, "device_id": None, "last_verified": None},
    "589az": {"is_used": False, "device_id": None, "last_verified": None},
    "719fd": {"is_used": False, "device_id": None, "last_verified": None},
    "801qp": {"is_used": False, "device_id": None, "last_verified": None},
    "479sj": {"is_used": False, "device_id": None, "last_verified": None},
    "251mf": {"is_used": False, "device_id": None, "last_verified": None},
    "940bc": {"is_used": False, "device_id": None, "last_verified": None},
    "407ze": {"is_used": False, "device_id": None, "last_verified": None},
    "137tn": {"is_used": False, "device_id": None, "last_verified": None},
    "766pw": {"is_used": False, "device_id": None, "last_verified": None},
    "361hi": {"is_used": False, "device_id": None, "last_verified": None},
    "658aj": {"is_used": False, "device_id": None, "last_verified": None},
    "986qx": {"is_used": False, "device_id": None, "last_verified": None},
    "349ue": {"is_used": False, "device_id": None, "last_verified": None},
    "594ky": {"is_used": False, "device_id": None, "last_verified": None},
    "877oz": {"is_used": False, "device_id": None, "last_verified": None},
    "685wt": {"is_used": False, "device_id": None, "last_verified": None},
    "119db": {"is_used": False, "device_id": None, "last_verified": None},
    "533xs": {"is_used": False, "device_id": None, "last_verified": None},
    "754lo": {"is_used": False, "device_id": None, "last_verified": None},
    "492at": {"is_used": False, "device_id": None, "last_verified": None},
    "628vu": {"is_used": False, "device_id": None, "last_verified": None},
    "986mp": {"is_used": False, "device_id": None, "last_verified": None},
    "303yc": {"is_used": False, "device_id": None, "last_verified": None},
    "845jh": {"is_used": False, "device_id": None, "last_verified": None},
    "656zn": {"is_used": False, "device_id": None, "last_verified": None},
    "209gl": {"is_used": False, "device_id": None, "last_verified": None},
        "7asf3z": {"is_used": False, "device_id": None, "last_verified": None},
    "d129az": {"is_used": False, "device_id": None, "last_verified": None},
    "xz084k": {"is_used": False, "device_id": None, "last_verified": None},
    "k2j97s": {"is_used": False, "device_id": None, "last_verified": None},
    "v6q39d": {"is_used": False, "device_id": None, "last_verified": None},
    "p93kd2": {"is_used": False, "device_id": None, "last_verified": None},
    "18azlm": {"is_used": False, "device_id": None, "last_verified": None},
    "c71mzu": {"is_used": False, "device_id": None, "last_verified": None},
    "r85fx1": {"is_used": False, "device_id": None, "last_verified": None},
    "a402tk": {"is_used": False, "device_id": None, "last_verified": None},
    "m3q7s9": {"is_used": False, "device_id": None, "last_verified": None},
    "z289sl": {"is_used": False, "device_id": None, "last_verified": None},
    "qz6u38": {"is_used": False, "device_id": None, "last_verified": None},
    "4jmw9p": {"is_used": False, "device_id": None, "last_verified": None},
    "98lcrv": {"is_used": False, "device_id": None, "last_verified": None},
    "ukd5a1": {"is_used": False, "device_id": None, "last_verified": None},
    "s0b2yw": {"is_used": False, "device_id": None, "last_verified": None},
    "kfg84n": {"is_used": False, "device_id": None, "last_verified": None},
    "nx93a7": {"is_used": False, "device_id": None, "last_verified": None},
    "1plze9": {"is_used": False, "device_id": None, "last_verified": None},
    "3cmx7q": {"is_used": False, "device_id": None, "last_verified": None},
    "p7zgb0": {"is_used": False, "device_id": None, "last_verified": None},
    "90akst": {"is_used": False, "device_id": None, "last_verified": None},
    "m97qcx": {"is_used": False, "device_id": None, "last_verified": None},
    "y24dnl": {"is_used": False, "device_id": None, "last_verified": None},
    "xn39e4": {"is_used": False, "device_id": None, "last_verified": None},
    "o648zd": {"is_used": False, "device_id": None, "last_verified": None},
    "64bnpy": {"is_used": False, "device_id": None, "last_verified": None},
    "hzx51r": {"is_used": False, "device_id": None, "last_verified": None},
    "a8y4kw": {"is_used": False, "device_id": None, "last_verified": None},
    "qkz75v": {"is_used": False, "device_id": None, "last_verified": None},
    "2rxw9a": {"is_used": False, "device_id": None, "last_verified": None},
    "kp29vn": {"is_used": False, "device_id": None, "last_verified": None},
    "sw8b41": {"is_used": False, "device_id": None, "last_verified": None},
    "b9xq20": {"is_used": False, "device_id": None, "last_verified": None},
    "d8pwzs": {"is_used": False, "device_id": None, "last_verified": None},
    "mr134n": {"is_used": False, "device_id": None, "last_verified": None},
    "z5qja3": {"is_used": False, "device_id": None, "last_verified": None},
    "v12zsf": {"is_used": False, "device_id": None, "last_verified": None},
    "ef47qx": {"is_used": False, "device_id": None, "last_verified": None},
    "cya970": {"is_used": False, "device_id": None, "last_verified": None},
    "73xfld": {"is_used": False, "device_id": None, "last_verified": None},
    "bnm4t7": {"is_used": False, "device_id": None, "last_verified": None},
    "v6u9cr": {"is_used": False, "device_id": None, "last_verified": None},
    "oz2klq": {"is_used": False, "device_id": None, "last_verified": None},
    "kqpz67": {"is_used": False, "device_id": None, "last_verified": None},
    "xs93tk": {"is_used": False, "device_id": None, "last_verified": None},
    "91tbez": {"is_used": False, "device_id": None, "last_verified": None},
    "34grzx": {"is_used": False, "device_id": None, "last_verified": None},
    "az98sn": {"is_used": False, "device_id": None, "last_verified": None},
    "ubm7cw": {"is_used": False, "device_id": None, "last_verified": None},
    "6jyxv5": {"is_used": False, "device_id": None, "last_verified": None},
    "c0zbd4": {"is_used": False, "device_id": None, "last_verified": None},
    "rpn81q": {"is_used": False, "device_id": None, "last_verified": None},
    "j4zyw1": {"is_used": False, "device_id": None, "last_verified": None},
    "q9xkls": {"is_used": False, "device_id": None, "last_verified": None},
    "e2fgm6": {"is_used": False, "device_id": None, "last_verified": None},
    "1mf07z": {"is_used": False, "device_id": None, "last_verified": None},
    "wqk781": {"is_used": False, "device_id": None, "last_verified": None},
    "4bcmzx": {"is_used": False, "device_id": None, "last_verified": None},
    "gqxfv2": {"is_used": False, "device_id": None, "last_verified": None},
    "v9mjts": {"is_used": False, "device_id": None, "last_verified": None},
    "akqyz6": {"is_used": False, "device_id": None, "last_verified": None},
    "ztr019": {"is_used": False, "device_id": None, "last_verified": None},
    "p84czw": {"is_used": False, "device_id": None, "last_verified": None},
    "6tbgwr": {"is_used": False, "device_id": None, "last_verified": None},
    "v1r80k": {"is_used": False, "device_id": None, "last_verified": None},
    "nzk4m2": {"is_used": False, "device_id": None, "last_verified": None},
    "3ewl7a": {"is_used": False, "device_id": None, "last_verified": None},
    "yq9mc8": {"is_used": False, "device_id": None, "last_verified": None},
    "84gqsz": {"is_used": False, "device_id": None, "last_verified": None},
    "bwxv60": {"is_used": False, "device_id": None, "last_verified": None},
    "a7jpzk": {"is_used": False, "device_id": None, "last_verified": None},
    "lz90aq": {"is_used": False, "device_id": None, "last_verified": None},
    "mpz724": {"is_used": False, "device_id": None, "last_verified": None},
    "tx7p1c": {"is_used": False, "device_id": None, "last_verified": None},
    "38plzx": {"is_used": False, "device_id": None, "last_verified": None},
    "k92slb": {"is_used": False, "device_id": None, "last_verified": None},
    "m3a7yu": {"is_used": False, "device_id": None, "last_verified": None},
    "57lgvo": {"is_used": False, "device_id": None, "last_verified": None},
    "fbqz96": {"is_used": False, "device_id": None, "last_verified": None},
    "vlpw32": {"is_used": False, "device_id": None, "last_verified": None},
    "0kcgyu": {"is_used": False, "device_id": None, "last_verified": None},
    "sgtyv3": {"is_used": False, "device_id": None, "last_verified": None},
    "k4p839": {"is_used": False, "device_id": None, "last_verified": None},
    "qmb267": {"is_used": False, "device_id": None, "last_verified": None},
    "y19lxw": {"is_used": False, "device_id": None, "last_verified": None},
          "019af3": {"is_used": False, "device_id": None, "last_verified": None},
    "019b7x": {"is_used": False, "device_id": None, "last_verified": None},
    "019czq": {"is_used": False, "device_id": None, "last_verified": None},
    "019d6k": {"is_used": False, "device_id": None, "last_verified": None},
    "019ek9": {"is_used": False, "device_id": None, "last_verified": None},
    "019flx": {"is_used": False, "device_id": None, "last_verified": None},
    "019g2r": {"is_used": False, "device_id": None, "last_verified": None},
    "019hvy": {"is_used": False, "device_id": None, "last_verified": None},
    "019ij5": {"is_used": False, "device_id": None, "last_verified": None},
    "019kz3": {"is_used": False, "device_id": None, "last_verified": None},
    "019lcp": {"is_used": False, "device_id": None, "last_verified": None},
    "019m1t": {"is_used": False, "device_id": None, "last_verified": None},
    "019nxb": {"is_used": False, "device_id": None, "last_verified": None},
    "019ozv": {"is_used": False, "device_id": None, "last_verified": None},
    "019py4": {"is_used": False, "device_id": None, "last_verified": None},
    "019qg8": {"is_used": False, "device_id": None, "last_verified": None},
    "019rsm": {"is_used": False, "device_id": None, "last_verified": None},
    "019st2": {"is_used": False, "device_id": None, "last_verified": None},
    "019tuq": {"is_used": False, "device_id": None, "last_verified": None},
    "019uex": {"is_used": False, "device_id": None, "last_verified": None},
    "019v1k": {"is_used": False, "device_id": None, "last_verified": None},
    "019wcz": {"is_used": False, "device_id": None, "last_verified": None},
    "019xlf": {"is_used": False, "device_id": None, "last_verified": None},
    "019yk3": {"is_used": False, "device_id": None, "last_verified": None},
    "019zv7": {"is_used": False, "device_id": None, "last_verified": None},
    "019a5d": {"is_used": False, "device_id": None, "last_verified": None},
    "019bq1": {"is_used": False, "device_id": None, "last_verified": None},
    "019cpt": {"is_used": False, "device_id": None, "last_verified": None},
    "019dlo": {"is_used": False, "device_id": None, "last_verified": None},
    "019e8x": {"is_used": False, "device_id": None, "last_verified": None},
    "019fmr": {"is_used": False, "device_id": None, "last_verified": None},
    "019g0z": {"is_used": False, "device_id": None, "last_verified": None},
    "019hnq": {"is_used": False, "device_id": None, "last_verified": None},
    "019i7k": {"is_used": False, "device_id": None, "last_verified": None},
    "019jp4": {"is_used": False, "device_id": None, "last_verified": None},
    "019kcb": {"is_used": False, "device_id": None, "last_verified": None},
    "019lzv": {"is_used": False, "device_id": None, "last_verified": None},
    "019m5g": {"is_used": False, "device_id": None, "last_verified": None},
    "019nq9": {"is_used": False, "device_id": None, "last_verified": None},
    "019ok7": {"is_used": False, "device_id": None, "last_verified": None},
    "019pwy": {"is_used": False, "device_id": None, "last_verified": None},
    "019qz1": {"is_used": False, "device_id": None, "last_verified": None},
    "019rj6": {"is_used": False, "device_id": None, "last_verified": None},
    "019sdu": {"is_used": False, "device_id": None, "last_verified": None},
    "019tbv": {"is_used": False, "device_id": None, "last_verified": None},
    "019uk4": {"is_used": False, "device_id": None, "last_verified": None},
    "019vlm": {"is_used": False, "device_id": None, "last_verified": None},
    "019wcp": {"is_used": False, "device_id": None, "last_verified": None},
    "019xzn": {"is_used": False, "device_id": None, "last_verified": None},
    "019y9e": {"is_used": False, "device_id": None, "last_verified": None},
    "019zbt": {"is_used": False, "device_id": None, "last_verified": None},
    "019aov": {"is_used": False, "device_id": None, "last_verified": None},
    "019bz6": {"is_used": False, "device_id": None, "last_verified": None},
    "019c7k": {"is_used": False, "device_id": None, "last_verified": None},
    "019dpr": {"is_used": False, "device_id": None, "last_verified": None},
    "019e1y": {"is_used": False, "device_id": None, "last_verified": None},
    "019fut": {"is_used": False, "device_id": None, "last_verified": None},
    "019gkl": {"is_used": False, "device_id": None, "last_verified": None},
    "019hcb": {"is_used": False, "device_id": None, "last_verified": None},
    "019izp": {"is_used": False, "device_id": None, "last_verified": None},
    "019j7x": {"is_used": False, "device_id": None, "last_verified": None},
    "019k2d": {"is_used": False, "device_id": None, "last_verified": None},
    "019lqg": {"is_used": False, "device_id": None, "last_verified": None},
    "019moy": {"is_used": False, "device_id": None, "last_verified": None},
    "019n3k": {"is_used": False, "device_id": None, "last_verified": None},
    "019oxt": {"is_used": False, "device_id": None, "last_verified": None},
    "019pyf": {"is_used": False, "device_id": None, "last_verified": None},
    "019q6v": {"is_used": False, "device_id": None, "last_verified": None},
    "019rja": {"is_used": False, "device_id": None, "last_verified": None},
    "019szc": {"is_used": False, "device_id": None, "last_verified": None},
    "019tvb": {"is_used": False, "device_id": None, "last_verified": None},
    "019ug3": {"is_used": False, "device_id": None, "last_verified": None},
    "019vln": {"is_used": False, "device_id": None, "last_verified": None},
    "019w1t": {"is_used": False, "device_id": None, "last_verified": None},
    "019xrm": {"is_used": False, "device_id": None, "last_verified": None},
    "019yk4": {"is_used": False, "device_id": None, "last_verified": None},
    "019znw": {"is_used": False, "device_id": None, "last_verified": None},
    "019a3q": {"is_used": False, "device_id": None, "last_verified": None},
    "019bkp": {"is_used": False, "device_id": None, "last_verified": None},
    "019c4x": {"is_used": False, "device_id": None, "last_verified": None},
    "019dfu": {"is_used": False, "device_id": None, "last_verified": None},
    "019e79": {"is_used": False, "device_id": None, "last_verified": None},
    "019fls": {"is_used": False, "device_id": None, "last_verified": None},
    "019gcm": {"is_used": False, "device_id": None, "last_verified": None},
    "019hxz": {"is_used": False, "device_id": None, "last_verified": None},
    "019izq": {"is_used": False, "device_id": None, "last_verified": None},
    "019j9y": {"is_used": False, "device_id": None, "last_verified": None},
    "019kzr": {"is_used": False, "device_id": None, "last_verified": None},
    "019l6b": {"is_used": False, "device_id": None, "last_verified": None},
    "019mqf": {"is_used": False, "device_id": None, "last_verified": None},
    "019n8k": {"is_used": False, "device_id": None, "last_verified": None},
    "019owd": {"is_used": False, "device_id": None, "last_verified": None},
    "019pju": {"is_used": False, "device_id": None, "last_verified": None},
         "ADHAR-CUSTOM-48291": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-60174": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-27385": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-91740": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-30816": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-75962": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-84209": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-63915": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-13597": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-56041": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-39820": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-74026": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-24983": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-98437": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-32759": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-60128": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-19407": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-81953": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-30894": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-45610": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-70961": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-15830": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-68429": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-79015": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-91607": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-28341": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-47832": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-59124": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-16083": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-36489": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-97246": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-20359": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-45017": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-74120": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-38654": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-53701": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-80947": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-69215": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-14098": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-60428": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-95123": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-70835": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-29584": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-84160": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-17309": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-69024": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-47203": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-58392": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-76138": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-18365": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-92841": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-31760": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-50479": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-26531": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-83402": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-75210": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-48276": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-15409": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-62984": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-91582": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-24673": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-37045": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-80315": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-92068": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-45176": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-32487": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-74092": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-61047": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-57490": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-89130": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-30741": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-64819": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-73208": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-20538": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-89473": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-13084": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-57468": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-21697": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-45780": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-69234": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-81905": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-32516": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-15824": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-40261": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-50942": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-68093": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-73129": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-97384": {"is_used": False, "device_id": None, "last_verified": None},
    "ADHAR-CUSTOM-41526": {"is_used": False, "device_id": None, "last_verified": None},
    "9fa4c4ee5c": {"is_used": False, "device_id": None, "last_verified": None},
     "ffec8ee809": {"is_used": False, "device_id": None, "last_verified": None},
      "bd4b48b1ff": {"is_used": False, "device_id": None, "last_verified": None},
      "6e2315d291": {"is_used": False, "device_id": None, "last_verified": None},
      "58be7c1655": {"is_used": False, "device_id": None, "last_verified": None},
       "6c5dd505c4": {"is_used": False, "device_id": None, "last_verified": None},
        "d102084582": {"is_used": False, "device_id": None, "last_verified": None},
        "ADPMOBILE-CUSTOM-238": {"is_used": False, "device_id": None, "last_verified": None},
         "982d6f5ec5": {"is_used": False, "device_id": None, "last_verified": None},
    "1216S037": {"is_used": False, "device_id": None, "last_verified": None}, 
  "1216S492": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S708": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S154": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S980": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S361": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S226": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S577": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S843": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S695": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S419": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S060": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S308": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S774": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S189": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S650": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S235": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S991": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S578": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S824": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S443": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S018": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S394": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S167": {"is_used": False, "device_id": None, "last_verified": None},
  "1216S609": {"is_used": False, "device_id": None, "last_verified": None}


}

@app.route('/keys', methods=['GET'])
def verify_key():
    key = request.args.get('key')
    device_id = request.args.get('device_id')
    
    if not key or not device_id:
        return jsonify({"error": "Missing key or device ID"}), 400

    if key not in valid_keys:
        return jsonify({"error": "Invalid key"}), 401

    key_data = valid_keys[key]
    
    if key_data["is_used"] and key_data["device_id"] != device_id:
        return jsonify({"error": "Key already in use by another device"}), 403
        
    valid_keys[key] = {
        "is_used": True,
        "device_id": device_id,
        "last_verified": datetime.now().isoformat()
    }
    
    return jsonify({
        "success": True,
        "message": "Key verified successfully"
    })

@app.route('/ids', methods=['GET', 'POST'])
def manage_device_ids():
    if request.method == 'GET':
        # Return list of registered devices with their keys
        devices = {
            key: data["device_id"] 
            for key, data in valid_keys.items() 
            if data["is_used"]
        }
        return jsonify(devices)
    
    elif request.method == 'POST':
        device_id = request.data.decode('utf-8')
        key = request.args.get('key')
        
        if not device_id or not key:
            return jsonify({"error": "Missing device ID or key"}), 400
            
        if key not in valid_keys:
            return jsonify({"error": "Invalid key"}), 401
            
        key_data = valid_keys[key]
        
        if key_data["is_used"] and key_data["device_id"] != device_id:
            return jsonify({"error": "Key already in use"}), 403
            
        valid_keys[key]["device_id"] = device_id
        valid_keys[key]["is_used"] = True
        valid_keys[key]["last_verified"] = datetime.now().isoformat()
        
        return jsonify({
            "message": "Device registered successfully",
            "key": key
        }), 201

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=5000, debug=True)
